Fixes for vmware-esxi builder and any builders that the fuse scripts.
canonical/packer-maas pull request #131
Opened 2023-08-31 20:40 UTC by ThinGuy

Changes to vmware-esxi to build ESXi 8.0b
Change any call that attempts `fusermount -u` to `fusermount -z -u`

2023-08-31 23:38 UTC, CodeBleu commented
@ThinGuy I was looking around to see if any newer forks had any updates in them to fix the fuse stuff, and possibly Fedora38 OS as well...or any Fedora Server for that matter.  I then found your fork and was noticing you knocking stuff out.  Appreciate it! 

I'm assuming this will fix #126 ?

2023-09-01 21:08 UTC, ThinGuy commented
> @ThinGuy I was looking around to see if any newer forks had any updates in them to fix the fuse stuff, and possibly Fedora38 OS as well...or any Fedora Server for that matter. I then found your fork and was noticing you knocking stuff out. Appreciate it!
> 
> I'm assuming this will fix #126 ?

I hope so! Currently, rhel 9.2 builds clean but the installation hits the 30-minute timeout.  Curtin runs without error, server is set up correctly, but it never tells MAAS that the installation is completed.

2023-09-05 19:04 UTC, alexsander-souza requested changes
awesome job, but it needs some tweaks

2023-09-05 19:04 UTC, alexsander-souza commented on vmware-esxi/KS.CFG
> -# vim-cmd hostsvc/enable_ssh
we should keep this disabled, it may pose a security risk for some users and we don't have a good way to alert them of this change.

2023-09-05 19:04 UTC, alexsander-souza commented on vmware-esxi/KS.CFG
> +vim-cmd hostsvc/enable_esx_shell
same as above, keep this disabled

2023-09-05 19:04 UTC, alexsander-souza commented on rhel9/Makefile
> +	@if [ $(shell lsb_release -sr|cut -d. -f1) -le 20 ];then \
```suggestion
	@if [ $(shell lsb_release -sr|cut -d. -f1) -ge 22 ];then \
	  dpkg -s libnbd-bin nbdkit packer fuse2fs > /dev/null;  \
	else \
 	  dpkg -s libnbd0 nbdkit packer fuse2fs > /dev/null; \
 	fi
```

2023-09-05 19:04 UTC, alexsander-souza commented on rhel9/README.md
> +* packer - from Hashicorp repository, v1.9.0 or newer
keep the reference to Packer install page. It's easier to keep docs up to date if we rely on external resources.

2023-09-05 19:04 UTC, alexsander-souza commented on ubuntu/Makefile
> +	@if [ $(shell lsb_release -sr|cut -d. -f1) -le 20 ];then \
see suggestion in the RHEL makefile above

2023-09-05 19:04 UTC, alexsander-souza commented on vmware-esxi/Makefile
> +	@if [ $(shell lsb_release -sr|cut -d. -f1) -le 20 ];then \
see suggestion in the makefiles above

2023-09-05 19:04 UTC, alexsander-souza commented on vmware-esxi/vmware-esxi.pkr.hcl
> +  memory           = 8192
it this really necessary?

2023-09-14 14:43 UTC, alexsander-souza commented
superseded by #137, #138, #139 and #140

2023-09-14 14:43 UTC, closed without merging