feat: add alma8 and alma9 packer configs
canonical/packer-maas pull request #207
Opened 2024-02-12 21:42 UTC by lleyton

These are mainly just copies of the Rocky configs, but with the alma repos instead.

2024-03-01 18:00 UTC, alexsander-souza requested changes
awesome work, but the alma9 template need some changes.

basically just do the same changes done to alma8 to use the packer template file format and variable expansion.

2024-03-01 18:00 UTC, alexsander-souza commented on alma9/Makefile
> +http/alma.ks: http/alma.ks.in
remove this

2024-03-01 18:00 UTC, alexsander-souza commented on alma9/README.md
> +export KS_PROXY="--proxy=\"${HTTP_PROXY}\""
update to new format

2024-03-01 18:00 UTC, alexsander-souza commented on alma9/alma9.pkr.hcl
> +
add variables for mirrors

2024-03-01 18:00 UTC, alexsander-souza commented on alma9/alma9.pkr.hcl
> +  shutdown_timeout = "1h"
add template expansion

2024-03-01 18:00 UTC, alexsander-souza commented on alma9/http/alma.ks.in
convert to packer template file

2024-03-04 10:36 UTC, lleyton commented
Just impled the suggestions, let me know if it looks good now

2024-03-04 13:36 UTC, SK1Y101 commented
Hi @lleyton, just hoping in to confirm that your alma9 changes allow the image to be built with the proxy settings as expected with the current packer version as expected!

2024-03-04 13:47 UTC, alexsander-souza approved these changes
all good, lgtm

2024-03-04 13:48 UTC, merged