Add CentOS 8 Stream (latest) Packer template
canonical/packer-maas pull request #52
Opened 2022-06-21 12:37 UTC by rothbauer

It is just a modified centos8 template, but fully working.

Would be cool if you could add it to mainstream MAAS as well.

2022-06-24 21:19 UTC, alexsander-souza requested changes
Nice work. Please update the README with the current version of the requirements.

2022-06-24 21:19 UTC, alexsander-souza commented on centos8-stream/README.md
> +* A machine running Ubuntu 18.04+ with the ability to run KVM virtual machines.
Bump to 22.04

2022-06-24 21:19 UTC, alexsander-souza commented on centos8-stream/README.md
> +* [MAAS](https://maas.io) 2.3+, [MAAS](https://maas.io) 2.7+ recommended
Bump to MAAS 3.0 (oldest version currently supported) and 3.2 (current stable version)

2022-06-24 21:19 UTC, alexsander-souza commented on centos8-stream/README.md
> +* [Curtin](https://launchpad.net/curtin) 19.3-792+
Bump to Curtin 21+

2022-06-30 07:54 UTC, rothbauer commented on centos8-stream/README.md
> +* [Curtin](https://launchpad.net/curtin) 19.3-792+
Done, versions changed as requested.

2022-06-30 14:41 UTC, alexsander-souza approved these changes
Thanks for the fixes. We are good to land this now

2022-06-30 16:11 UTC, merged